# Generated by Django 4.2.5 on 2023-09-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortenner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='origin',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
